# Generated by Django 3.2.4 on 2021-06-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='token',
            field=models.TextField(default='no token - provide for this'),
        ),
    ]
